---
###############################################################################
# Dropbear Config
###############################################################################
# Set configuration file, host keys, optionally removing install generated host
# keys, and set authorized_keys file options.
#
# Reference:
# * https://linuxconfig.org/how-to-install-and-configure-dropbear-on-linux

- name: '{{ "Config | filesystem | set " ~ dropbear___app._cfg }}'
  notify: 'Handlers | dropbear'
  ansible.builtin.template:
    src: 'dropbear.conf.j2'
    dest: '{{ dropbear___app._cfg }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
    force: true

- name: 'Config | filesystem | remove unused host keys'
  when: dropbear__srv._remove_unused_keys
  notify: 'Handlers | dropbear'
  ansible.builtin.file:
    path: '{{ dropbear___app._etc_d ~ "/dropbear_" ~ item ~ "_host_key" }}'
    state: 'absent'
  loop: '{{
      dropbear___app._valid_key_types |
      difference([dropbear__cfg._host_key_type])
    }}'

- name:
    '{{ "Config | filesystem | set " ~ dropbear__cfg._host_key_dest_file }}'
  when: dropbear__cfg._host_key_file | length > 0
  notify: 'Handlers | dropbear'
  ansible.builtin.copy:
    src: '{{ dropbear__cfg._host_key_file }}'
    dest: '{{ dropbear__cfg._host_key_dest_file }}'
    owner: 'root'
    group: 'root'
    mode: '0600'
    force: true

- name:
    '{{ "Config | filesystem | set " ~ dropbear___app._authorized_keys_file }}'
  notify: 'Handlers | dropbear'
  ansible.builtin.copy:
    content: '{{ dropbear__cfg._authorized_key_file }}'
    dest: '{{ dropbear___app._authorized_keys_file }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
    force: true
