---
###############################################################################
# Dropbear Service
###############################################################################
#
# Reference:
# * https://linuxconfig.org/how-to-install-and-configure-dropbear-on-linux

- name: 'Install packages'
  ansible.builtin.include_role:
    name: 'r_pufky.srv.apt'
  vars:
    apt_packages:
      - '{{ dropbear_role_packages }}'
    apt_package_update_cache: true

- name: 'Prep'
  ansible.builtin.include_tasks: 'prep.yml'
- name: 'Config'
  ansible.builtin.include_tasks: 'config.yml'
