---
###############################################################################
# Dropbear Prep
###############################################################################
# Assert host key type is correct if set.

- name: 'Prep | fact | record start time'
  ansible.builtin.set_fact:
    dropbear__srv: "{{ {} | r_pufky.data.v3(

        _remove_unused_keys=dropbear_srv_remove_unused_keys,
        _options=dropbear_srv_options,
        _ifdown=dropbear_srv_ifdown,
        _shutdown_timeout=dropbear_srv_shutdown_timeout,
      ) }}"
    dropbear__cfg: "{{ {} | r_pufky.data.v3(

        _start=now(utc=True, fmt='%Y-%m-%dT%H%M%S'),
        _host_key_file=dropbear_cfg_host_key_file,
        _host_key_type=(
          dropbear_cfg_host_key_file.rsplit('/')[-1].split('_')[1]
        ),
        _host_key_dest_file=(
          dropbear___app._etc_d ~ '/dropbear_' ~
          dropbear_cfg_host_key_file.rsplit('/')[-1].split('_')[1] ~
          '_host_key'
        ),
        _authorized_key_file=dropbear_cfg_authorized_key_file,
      ) }}"

- name: 'Prep | assert | valid host key type'
  when: dropbear__cfg._host_key_file | length > 0
  ansible.builtin.assert:
    quiet: true
    that:
      - dropbear__cfg._host_key_type in dropbear___app._valid_key_types
    fail_msg: |

      ✘ dropbear_cfg_host_key_file incorrect.

      dropbear_cfg_host_key_file: {{ dropbear_cfg_host_key_file }}
      Must be one of: {{ dropbear___app._valid_key_types | join(", ") }}.
