---
###############################################################################
# Dropbear Handlers
###############################################################################

- name: 'Handlers | update-initramfs'
  listen: 'Handlers | update dropbear'
  ansible.builtin.command: 'update-initramfs -u'
  changed_when: true

- name: 'Handlers | update-grub'
  listen: 'Handlers | update dropbear'
  ansible.builtin.command: 'update-grub'
  changed_when: true
