---
- name: 'Default | converge'
  hosts: 'all'
  become: true
  tasks:
    - name: 'Default | converge | apply r_pufky.deb.dropbear'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.dropbear'
