---
###############################################################################
# Default
###############################################################################
# Default configuration is deployed successfully.
#
# Network level testing requires VMs for kernel namespace and systemd
# networking without affecting host.
#
# Keys are randomly generated test keys.
#
# Tests:
# * Unused host keys are removed.
# * dropbear.conf is rendered correctly.
# * Binary host key is copied correctly.

dependency:
  name: 'galaxy'
driver:
  name: 'vagrant'
  provider:
    name: 'libvirt'
    type: 'libvirt'
provisioner:
  name: 'ansible'
  connection_options:
    ansible_ssh_user: 'vagrant'
    ansible_become: true
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
  inventory:
    group_vars:
      all:
        apt_srv_auto_grub_boot: true  # Testing VM only.
        dropbear_cfg_host_key_file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/files/dropbear_rsa_host_key"
          }}'
        dropbear_srv_remove_unused_keys: true
        dropbear_cfg_authorized_key_file: '{{
            lookup("file",
              lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                     "/molecule/files/id_dropbear.pub")
          }}'
platforms:
  - name: 'dropbear-default'
    box: 'debian/trixie64'
    memory: 4096
    cpus: 2
    interfaces:
      - network_name: 'private_network'
        auto_config: true
        type: 'dhcp'
verifier:
  name: 'ansible'
scenario:
  test_sequence:
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'converge'
    - 'idempotence'
    - 'verify'
    - 'destroy'
